# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5178491023486bae558aed254652027b2c49146eb86d0d4c1f8d4d1bf319f6ba222a8f1892460e9dc8fcfc21ee75c4648d86f0e901cadabc9425bcfbf55d823b

test:
  secret_key_base: b66530ed148e7a0937357fc08178524a8adabcf980dc0d623e722b2e54ad42604c43ee7bb99fa872d33b0dec8f02ff7d2d33fe65f16de765c0f2c0181c95b563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
